# https://github.com/typeorm/typeorm/blob/master/docs/zh_CN/using-ormconfig.md
default:
  type: postgres
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  database: moviebay
  synchronize: true
  logging: false
  entities:
    - dist/modules/**/*.entity.js
  # https://github.com/typeorm/typeorm/blob/master/docs/zh_CN/migrations.md
  migrations:
    - dist/modules/**/*.migration.js
  # https://github.com/typeorm/typeorm/blob/master/docs/zh_CN/listeners-and-subscribers.md
  subscribers:
    - dist/modules/**/*.subscriber.js