name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
        mkdir -p ~/.ssh/
        echo "$ACCESS_TOKEN" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global user.name  'lugavin'
        git config --global user.email 'lugavin@outlook.com'

    - name: Build
      run: |
        npm install
        npm run build

    # https://cli.vuejs.org/zh/guide/deployment.html#github-pages
    - name: Deploy
      run: |
        cd dist
        git init
        git add -A
        git commit -m 'deploy'
        git push git@github.com:lugavin/lugavin.github.io.git master
        #git push git@github.com:lugavin/lugavin.github.io.git master:moviebay
        
    #- name: Deploy
    #  uses: JamesIves/github-pages-deploy-action@releases/v3
    #  with:
    #    ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    #    BASE_BRANCH: master # The branch the action should deploy from.
    #    BRANCH: gh-pages    # The branch the action should deploy to.
    #    FOLDER: dist        # The folder the action should deploy.
